# version: "3.9"

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - php
      - mysql
    container_name: nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./../html/:/var/www/html
    networks:
      - laravel
  
  php:
    build: 
      context: .
      dockerfile: php${PHP_VERSION}.dockerfile
    image: runaphp:v${PHP_VERSION}
    container_name: php
    volumes:
      - ./../html/:/var/www/html
    networks:
      - laravel
    env_file:
      - .env

  mysql:
    image: mysql:${MYSQL_VERSION}
    platform: linux/amd64
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_DBPORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_DBUSER}
      MYSQL_PASSWORD: ${MYSQL_DBPASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - laravel

  # npm:
  #   image: node:current-alpine
  #   container_name: npm
  #   volumes:
  #     - ./../html/:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ['npm']
  #   networks:
  #     - laravel
  python:
    build: ./app
    container_name: python_converter
    volumes:
      - ./app:/app  # Código Python
      - ./../html/runachay7/public/uploads:/app/uploads  # 🔹 Python ahora usa la misma carpeta de Laravel
    working_dir: /app
    ports:
      - "5000:5000"
    networks:
      - laravel
    
networks:
  laravel:
    name: laravel

